[tool.poetry]
name = "wizard"
version = "0.2.0"
description = "A tool for searching and extracting article metadata from the CAPES Periodicals Portal."
authors = ["Daniel Amaral <silva.daniel86@gmail.com>", "CAPES Research Wizard Team"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: GUI",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
packages = [{include = "wizard", from = "src"}]
repository = "https://github.com/damarals/wizard"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/damarals/wizard/issues"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pyside6 = "^6.8.2.1"
requests = "^2.32.3"
beautifulsoup4 = "^4.13.3"
pandas = "^2.2.3"
pytablericons = "^1.0.1"
pyqtdarktheme = "^2.1.0"


[tool.poetry.scripts]
wizard = "wizard.main:main"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.0.0"

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-v --cov=wizard"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
